version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d/
      - ./.env:/docker-entrypoint-initdb.d/.env